import csv
import meraki
from rich import print as rprint
from env import API_KEY, ORG_ID

DASHBOARD = meraki.DashboardAPI(API_KEY)
CSV_FILE = 'ssid-export.csv'

def get_networks(orgId):
    """going to take in an Organization ID and return all the Network ID's that have 
    wireless appliances in them"""
    org_response = DASHBOARD.organizations.getOrganizationNetworks(orgId)
    # Create a list object of all Network ID's assocaited to the Org ID
    all_networks = []
    for network in org_response:
        for products in network['productTypes']:
            if products == 'wireless':
                all_networks.append(network['id'])
    return all_networks

def get_network_info(netIds):
    """this function is going to take in a list of Network ID's generated by the above function and 
    get the SSID information for each network. Once the SSID information has been found, it is going 
    to break up the required SSID information into a list and send that off to the CSV writter function."""
    for netId in netIds:
        net_response = DASHBOARD.wireless.getNetworkWirelessSsids(netId)
        
        ssid_data = []
        for ssid in net_response:
            name = ssid['name']
            enabled = ssid['enabled']
            ipAssign = ssid['ipAssignmentMode']
            visible = ssid['visible']
            if ssid['authMode'] == 'open':
                password = 'Open - No Password'
            elif ssid['authMode'] == 'psk':
                password = ssid['psk']
            else:
                password = "Unknown"
            ssid_data = [ORG_ID, netId, name, password, enabled, ipAssign, visible]
            csv_writer(ssid_data)

def csv_writer(data):
    """this function takes in a list of data generated from the get_network_info() function and 
    writes it to a CSV file"""
    with open(CSV_FILE, mode='a') as f:
        csvwriter = csv.writer(f)
        csvwriter.writerow(data)

if __name__ == "__main__":
    network_data = get_networks(ORG_ID)
    get_network_info(network_data)
